name: flutter_agent_panel
description: "A modern multi terminal application for AI agent."
publish_to: 'none'

version: 0.0.8+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  xterm: 
    path: ./packages/xterm
  flutter_pty: 
    path: ./packages/flutter_pty
  window_manager: ^0.5.1
  path_provider: ^2.1.5
  uuid: ^4.5.1
  flutter_screenutil: ^5.9.3
  flutter_localizations:
    sdk: flutter
  collection: ^1.19.0
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  equatable: ^2.0.7
  file_picker: ^10.3.8
  shadcn_ui: ^0.43.0
  url_launcher: ^6.3.1
  auto_route: ^11.1.0
  gap: ^3.0.1
  path: ^1.9.1
  chinese_font_library: ^1.2.0
  package_info_plus: ^9.0.0
  updat: ^1.4.0
  logger: ^2.6.2
  intl: ^0.20.2


workspace:
  - packages/xterm
  - packages/flutter_pty

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  lean_builder: ^0.1.6
  auto_route_generator: ^10.4.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/agent_logos/

flutter_launcher_icons:
  android: false
  ios: false
  image_path: "assets/images/app_icon.png"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"




